export const EVENT_NAMES = {
  NEW_CONNECTED: 'NEW_CONNECTED',
  TOTAL_CLIENTS: 'TOTAL_CLIENTS',
  INCOMING_CHAT: 'INCOMING_CHAT',
  DISCONNECTED: 'DISCONNECTED',
  SOMEONE_TYPING: 'SOMEONE_TYPING',
} as const
